#define         REG1                  R4
#define         REG2                  R5
#define         REG3                  R6
#define         REG4                  R7
#define         REG5                  R8
#define         REG6                  R9
#define         REG7                  R10
#define         REG8                  R11
#define         REG9                  R12
#define         REG10                 R13
//#define         ADCBufInPnt           R14
//#define         ChannelNumber         R15
